export function buildMapProperty(overrides?: Partial<Record<string, unknown>>) {
  return {
    propertyId: "property_1",
    address: "17 Summer St",
    city: "Worcester",
    state: "MA",
    postalCode: "01608",
    lat: 42.2626,
    lng: -71.8023,
    mapState: "opportunity",
    followUpState: "due_today",
    visitCount: 2,
    notHomeCount: 0,
    lastVisitOutcome: "opportunity",
    leadId: "lead_1",
    leadStatus: "Connected",
    appointmentAt: null,
    priorityScore: 91,
    priorityBand: "high",
    ...overrides
  };
}

export function buildPropertyDetail(overrides?: Partial<Record<string, unknown>>) {
  return {
    propertyId: "property_1",
    address: "17 Summer St",
    city: "Worcester",
    state: "MA",
    postalCode: "01608",
    lat: 42.2626,
    lng: -71.8023,
    mapState: "opportunity",
    followUpState: "due_today",
    visitCount: 2,
    notHomeCount: 0,
    lastVisitOutcome: "opportunity",
    lastVisitedAt: "2026-04-22T15:00:00.000Z",
    leadId: "lead_1",
    leadStatus: "Connected",
    ownerId: "user_1",
    firstName: "Jordan",
    lastName: "Lee",
    phone: "555-111-2222",
    email: "jordan@example.com",
    leadNotes: "Warm homeowner",
    interestLevel: "high",
    decisionMakerStatus: "all_present",
    preferredChannel: "text",
    bestContactTime: "Evenings",
    textConsent: true,
    objectionType: null,
    billReceived: false,
    proposalPresented: false,
    appointmentOutcome: null,
    rescheduleReason: null,
    cancellationReason: null,
    engagementScore: 4,
    cadenceTrack: "warm_with_contact",
    leadNextFollowUpAt: "2026-04-24T16:00:00.000Z",
    appointmentAt: null,
    priorityScore: 91,
    priorityBand: "high",
    prioritySummary: "High priority homeowner with active interest.",
    featureAccess: {
      mapEnabled: true,
      doorKnockingEnabled: true,
      visitLoggingEnabled: true,
      leadsEnabled: true,
      crmEnabled: true,
      appointmentsEnabled: true,
      selfImportsEnabled: true,
      advancedImportsEnabled: true,
      tasksEnabled: true,
      teamManagementEnabled: true,
      territoriesEnabled: true,
      solarCheckEnabled: true,
      importEnrichmentEnabled: true,
      bulkSolarEnrichmentEnabled: true,
      clusterAnalysisEnabled: true,
      premiumRoutingInsightsEnabled: true,
      datasetMarketplaceEnabled: true,
      enrichmentEnabled: true,
      priorityScoringEnabled: true,
      territoryPlanningEnabled: true,
      securityConsoleEnabled: true
    },
    recentVisits: [],
    recentActivities: [],
    facts: {
      beds: 3,
      baths: 2,
      squareFeet: 1800,
      lotSizeSqft: 7000,
      yearBuilt: 1978,
      lastSaleDate: null,
      lastSalePrice: null,
      propertyType: "single_family",
      listingStatus: null,
      saleType: null,
      daysOnMarket: null,
      hoaMonthly: null,
      dataCompletenessScore: 72,
      solarFitScore: 83,
      roofCapacityScore: 78,
      roofComplexityScore: 32,
      estimatedSystemCapacityKw: 8.4,
      estimatedYearlyEnergyKwh: 10800,
      solarImageryQuality: "good",
      propertyPriorityScore: 91,
      propertyPriorityLabel: "High"
    },
    enrichments: [],
    sourceRecords: [],
    ...overrides
  };
}

export function buildLeadDetail(overrides?: Partial<Record<string, unknown>>) {
  return {
    leadId: "lead_1",
    propertyId: "property_1",
    contactName: "Jordan Lee",
    ownerName: "E2E Owner",
    address: "17 Summer St",
    city: "Worcester",
    state: "MA",
    postalCode: "01608",
    firstName: "Jordan",
    lastName: "Lee",
    phone: "555-111-2222",
    email: "jordan@example.com",
    notes: "Initial note",
    leadStatus: "Connected",
    interestLevel: "high",
    cadenceTrack: "warm_with_contact",
    preferredChannel: "text",
    decisionMakerStatus: "all_present",
    bestContactTime: "Evenings",
    textConsent: true,
    billReceived: false,
    proposalPresented: false,
    objectionType: null,
    appointmentOutcome: null,
    rescheduleReason: null,
    cancellationReason: null,
    engagementScore: 4,
    nextFollowUpAt: "2026-04-24T16:00:00.000Z",
    appointmentAt: null,
    lastActivityAt: "2026-04-22T15:00:00.000Z",
    propertySummary: {
      lastVisitOutcome: "opportunity",
      lastVisitedAt: "2026-04-22T15:00:00.000Z",
      visitCount: 2
    },
    activities: [],
    tasks: [],
    recentActivity: [],
    ...overrides
  };
}

export function buildTeamMember(overrides?: Partial<Record<string, unknown>>) {
  return {
    memberId: "member_1",
    userId: "member_user_1",
    fullName: "Taylor Rep",
    email: "taylor@lumino.test",
    role: "rep",
    isActive: true,
    teamId: null,
    teamName: null,
    onboardingStatus: "active",
    invitedAt: "2026-04-20T12:00:00.000Z",
    joinedAt: "2026-04-20T13:00:00.000Z",
    lastSignInAt: "2026-04-22T13:00:00.000Z",
    ...overrides
  };
}
